title: Emily Elias # website title here
# logo:
description: >
    First Description
    <br><br>
    Second Description 
    <br><br>
    <a href="https://www.linkedin.com/in/emily-elias-043095ba/" style="color:#FFFF00">View my LinkedIn Profile</a>
theme: jekyll-theme-cayman